type: web
name: ai-study-pal
env: python
plan: free
buildCommand: "pip install -r requirements.txt"
startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2"
envVars:
key: PYTHON_VERSION
value: 3.11.9